name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: my-registry/sample-app:latest
      - name: Deploy to Kubernetes1
        uses: appleboy/kubectl-action@v1
        with:
          args: set image deployment/sample-app sample-app=my-registry/sample-app:latest
