# name: Build and Deploy
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Build Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: leepereira/sample-app:latest
      # - name: Deploy to Kubernetes
      #   uses: steebchen/kubectl-action@1.0.0
      #   with:
      #     args: set image deployment/sample-app sample-app=my-registry/sample-app:latest


name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Encode Docker Hub credentials
        run: |
          echo $DOCKER_USERNAME | base64 --decode > docker-username.txt
          echo $DOCKER_PASSWORD | base64 --decode > docker-password.txt
      - name: Echo Docker Hub credentials
        run: |
          echo "DOCKER_USERNAME: $(cat docker-username.txt)"
          echo "DOCKER_PASSWORD: $(cat docker-password.txt)"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: $(cat docker-username.txt)
          password: $(cat docker-password.txt)

