name: Login to Docker Hub

on:
  push:
    branches: main

jobs:
  registry_login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub1
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: leepereira/hayden:latest
          platform: linux/arm64

  my-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Check if Azure CLI is installed
        run: az --version


  my-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Azure CLI is installed
        run: az --version

  Authenticate_Azure_K8s:
    needs: [registry_login]
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
          tenant: ${{ secrets.AZURE_TENANT }}

      # - name: Set Kubectl Context
      #   uses: Azure/k8s-set-context@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBECONFIG }}
      #     context: ${{ secrets.KUBE_CONTEXT }}

      # - name: Verify Connection
      #   run: kubectl cluster-info