name: Login to Docker Hub

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub1
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: leepereira/hayden:latest
          platform: linux/arm64

